version: '3.9'
services:
  app:
    container_name: c-dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      tags:
        - druxx/dockerfile-layers:demo
        - druxx/udockerfile-layers:latest
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    volumes:
      - ./project:/project
    restart: unless-stopped
